version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14.14.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:14.14.0
    steps:
      - checkout
      - run:
          name: Connect via SSH and run deploy script
          command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./deploy_backend.sh”
          
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
