version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.14.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test
